/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uthh.edd.unidad1.proyecto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * autor: Angel Uriel Espinoza Alvarado
 */
public class FrmReportes extends javax.swing.JFrame {
    
    
  // Variables globales para guardar los datos recibidos de la taquilla
    private tdaBoletoCine[] lista;
    private int totalVentas;

    // Constructor que recibe el arreglo de boletos y la cantidad de ventas registradas
    public FrmReportes(tdaBoletoCine[] lista, int totalVentas) {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla

        // Guardamos los datos que nos enviaron desde la taquilla
        this.lista = lista;
        this.totalVentas = totalVentas;

        // Llamamos al metodo para que la tabla se cargue al abrir la ventana
        cargarTabla();
    }

    // Metodo para llenar la tabla y sumar los totales
    public void cargarTabla() {
        // Obtenemos el modelo de la tabla para manipular sus filas
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        modelo.setRowCount(0); // Limpia las filas para que no se dupliquen al dar clic en actualizar

        // Variables acumuladoras para los totales inferiores
        int sumaBoletos = 0;
        double sumaDinero = 0.0;

        // Ciclo for para recorrer unicamente las ventas realizadas
        for (int i = 0; i < totalVentas; i++) {
            tdaBoletoCine b = lista[i];

            // Verificamos si el boleto es VIP usando herencia
            String esVip;
            if (b instanceof tdaBoletoVip) {
                esVip = "Si";
            } else {
                esVip = "No";
            }

            // Acumulamos la cantidad de boletos y el dinero recaudado
            sumaBoletos = sumaBoletos + b.getCantBoletos();
            sumaDinero = sumaDinero + b.calcularTotal();

            // Creamos un arreglo para la fila con las 6 columnas
            Object[] fila = new Object[6];
            fila[0] = b.getFolio();          // Columna 1: Folio
            fila[1] = b.getCliente();        // Columna 2: Nombre del cliente
            fila[2] = b.getPelicula();       // Columna 3: Pelicula
            fila[3] = b.getCantBoletos();    // Columna 4: Cantidad de boletos
            fila[4] = esVip;                 // Columna 5: Tipo de sala (VIP o Normal)
            fila[5] = b.calcularTotal();     // Columna 6: Total cobrado

            // Agregamos la fila a la tabla
            modelo.addRow(fila);
        }

        // Mostramos los resultados finales en las etiquetas inferiores
        lblBoletosVendidos.setText(sumaBoletos + "");
        lblTotal.setText("$" + sumaDinero);
    }

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblBoletosVendidos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reporte de Ventas");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Cliente", "Pelicula", "Cantidad", "VIP", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Total de boletos vendidos:");

        lblBoletosVendidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBoletosVendidos.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Total recaudado:");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setText("0");

        btnCerrar.setBackground(new java.awt.Color(180, 20, 30));
        btnCerrar.setForeground(java.awt.Color.white);
        btnCerrar.setText("Cerrar ventana");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(211, 211, 211))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBoletosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblBoletosVendidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblTotal))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // Cierra unicamente la ventana de reportes sin detener la aplicacion
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBoletosVendidos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
