/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uthh.edd.unidad1.proyecto;

/**
 *
 * autor: Angel Uriel Espinoza Alvarado
 */
public class FrmTaquillaCine extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmTaquillaCine.class.getName());
  // arreglo unidimensional para registrar hasta 100 boletos
    private tdaBoletoCine[] listaBoletos = new tdaBoletoCine[100];
    
    // Contador de ventas registradas
    private int totalVentas = 0;
    
    public FrmTaquillaCine() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        // Evita que el usuario altere manualmente la clasificacion
        txtClasificacion.setEditable(false);
        
        // Asigna la clasificacion inicial segun la primera pelicula
        actualizarClasificacion();
    }
// Asigna la clasificacion segun la pelicula seleccionada
    private void actualizarClasificacion() {
        String pelicula = String.valueOf(cmbPelicula.getSelectedItem()).trim();

        switch (pelicula) {
            case "Spiderman":
            case "Cars 1":
            case "Toy Story":
                txtClasificacion.setText("A");
                break;
            case "Avengers Doomsday":
            case "Rapidos y Furiosos":
                txtClasificacion.setText("B");
                break;
            case "La Odisea":
                txtClasificacion.setText("C");
                break;
            default:
                txtClasificacion.setText("A");
                break;
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        cmbPelicula = new javax.swing.JComboBox<>();
        spnCantidad = new javax.swing.JSpinner();
        chkSalaVip = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        spnCombo = new javax.swing.JSpinner();
        btnVender = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRecibo = new javax.swing.JTextArea();
        lblClasificacion = new javax.swing.JLabel();
        txtClasificacion = new javax.swing.JTextField();
        spnEdad = new javax.swing.JSpinner();
        btnVerReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de taquillas de cine");

        jLabel2.setText("Elaboro: Angel Uriel Espinoza Alvarado 4\"C\"");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Folio: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Pelicula;");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cantidad de boletos: ");

        cmbPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spiderman ", "Cars 1 ", "La Odisea ", "Toy Story ", "Avengers Doomsday ", "Rapidos y Furiosos ", " " }));
        cmbPelicula.addActionListener(this::cmbPeliculaActionPerformed);

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        chkSalaVip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkSalaVip.setText("Sala VIP");
        chkSalaVip.addActionListener(this::chkSalaVipActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Combos Palomitas");

        spnCombo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        btnVender.setBackground(new java.awt.Color(20, 160, 20));
        btnVender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("Vender");
        btnVender.setToolTipText("");
        btnVender.addActionListener(this::btnVenderActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(180, 20, 30));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        txtRecibo.setEditable(false);
        txtRecibo.setBackground(new java.awt.Color(249, 255, 255));
        txtRecibo.setColumns(20);
        txtRecibo.setRows(5);
        jScrollPane1.setViewportView(txtRecibo);

        lblClasificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClasificacion.setText("Clasificación");

        txtClasificacion.setEditable(false);

        spnEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        btnVerReportes.setBackground(new java.awt.Color(0, 0, 128));
        btnVerReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReportes.setText("Ver reportes");
        btnVerReportes.addActionListener(this::btnVerReportesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFolio, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(cmbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(chkSalaVip)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblClasificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerReportes)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cmbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblClasificacion)
                                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkSalaVip)
                                    .addComponent(jLabel9)
                                    .addComponent(spnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerReportes)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSalaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSalaVipActionPerformed
         // Habilita o deshabilita el spinner de combos segun el estado del checkbox
        if (chkSalaVip.isSelected()) {
            spnCombo.setEnabled(true);
        } else {
            spnCombo.setValue(0); // Reinicia los combos a cero si se desmarca
        }
    }//GEN-LAST:event_chkSalaVipActionPerformed

    private void cmbPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeliculaActionPerformed
        actualizarClasificacion();
    }//GEN-LAST:event_cmbPeliculaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Limpia las cajas de texto y el area de recibo
        txtFolio.setText("");
        txtCliente.setText("");
        txtRecibo.setText("");
        
        // Restablece los spinners a sus valores iniciales
        spnEdad.setValue(1);
        spnCantidad.setValue(1);
        spnCombo.setValue(0);
        
        // Desmarca la casilla VIP
        chkSalaVip.setSelected(false);
        
        // Regresa el combo a la primera pelicula y actualiza su clasificacion
        cmbPelicula.setSelectedIndex(0);
        actualizarClasificacion();
        
        // Coloca el foco en el primer campo de captura
        txtFolio.requestFocus();        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
       // Obtener datos de la pantalla
        String folio = txtFolio.getText();
        String cliente = txtCliente.getText();
        int edad = (int) spnEdad.getValue();
        int cantidad = (int) spnCantidad.getValue();
        int combos = (int) spnCombo.getValue();
        String pelicula = cmbPelicula.getSelectedItem().toString();
        String clasificacion = txtClasificacion.getText();

        // Validar la venta de acuerdo a su edad
        if (clasificacion.equals("B") && edad < 12) {
            txtRecibo.setText("No se puede vender el boleto");
            return;
        }
        if (clasificacion.equals("C") && edad < 18) {
            txtRecibo.setText("No se puede vender el boleto");
            return;
        }

        double precioBase = 70.0;
        double cargoVip = 50.0;
        double costoCombo = 85.0;
        
        tdaBoletoCine nuevoBoleto;
        String tipoSala;
        double precioBoleto;

        if (chkSalaVip.isSelected()) {
            tipoSala = "VIP";
            // Para mostrar $120.0 en el ticket:
            precioBoleto = precioBase + cargoVip; 
            // Al objeto le pasamos el precio base (70.0) y el extra (50.0):
            nuevoBoleto = new tdaBoletoVip(folio, cliente, edad, pelicula, cantidad, precioBase, cargoVip);
        } else {
            tipoSala = "Tradicional";
            precioBoleto = precioBase; // Muestra $70.0
            nuevoBoleto = new tdaBoletoCine(folio, cliente, edad, pelicula, cantidad, precioBase);
        }

        // Guardar en el arreglo y contar venta
        listaBoletos[totalVentas] = nuevoBoleto;
        totalVentas++;
        
        // Obtenemos el descuento aplicado mediante el metodo recursivo
        double descuento = nuevoBoleto.calcularDescuentoRecursivo(cantidad);

        // Calcular el total a pagar
        double totalFinal = nuevoBoleto.calcularTotal() + (combos * costoCombo);

        // Imprimir ticket detallado
        txtRecibo.setText(" TICKET DE VENTA \n"
                + "Folio: " + folio + "\n"
                + "Cliente: " + cliente + "\n"
                + "Edad: " + edad+"\n"
                + "Pelicula: " + pelicula + "\n"
                + "Clasificacion: " + clasificacion + "\n"
                + "Tipo de Sala: " + tipoSala + "\n"
                + "Precio boleto: $" + precioBoleto + "\n"
                + "Cantidad boletos: " + cantidad + "\n"
                + "Descuento aplicado: "+ descuento+"\n"      
                + "Precio combo: $" + costoCombo + "\n"
                + "Combos palomitas: " + combos + "\n"
                + "Total a pagar: $" + totalFinal + "\n");
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnVerReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReportesActionPerformed
        // Crea y abre la ventana de reportes enviando la lista y el contador actual
        new FrmReportes(listaBoletos, totalVentas).setVisible(true);
    }//GEN-LAST:event_btnVerReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmTaquillaCine().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVerReportes;
    private javax.swing.JCheckBox chkSalaVip;
    private javax.swing.JComboBox<String> cmbPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasificacion;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnCombo;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextArea txtRecibo;
    // End of variables declaration//GEN-END:variables
}
